- name: Upgrade system
  apt:
   upgrade: dist
   update_cache: yes

- name: Install HAProxy
  apt:
    pkg:
      - haproxy
      - haproxy-log-analysis
      - haproxyctl
      - hatop
 
- name: HAProxy installed
  package:
      name: haproxy
      state: present

- name: Configure HAProxy
  template:
    src: roles/lb/template/haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: Restart HAProxy
  systemd:
      name: haproxy
      daemon_reload: yes
      state: restarted
      enabled: yes
